### PR TITLE
Some fixes and update to jmeter 2.13

### PR DESCRIPTION
**Pull request by micking**
I had the same problem as described in the Chocolatey discussion section of the jmeter package.
The error was caused by the fact that nuget creates the folder c:\ProgramData\chocolatey\lib\jmeter\ but chocolateyInstall.ps1 assumes the path would be c:\ProgramData\chocolatey\lib\jmeter.2.12\

### CODE REVIEW

**Comment by dgfitch** [comment]
Thanks much @micking!

**Comment by micking** [comment]
Would be great if you can update the package on chocolatey - if the new version works ok for you ;-)

**Comment by dgfitch** [comment]
Yeah, I'll try to do that shortly here - I need to figure out how to fix the icon and license as well.

**Comment by dgfitch** [comment]
Awaiting moderation, clean install/uninstall passes for me: https://chocolatey.org/packages/jmeter/2.13

Thanks again.

**Pull request merged**
